server {
  # Chỉ lắng nghe ở port 80 (sau đó Docker sẽ map nó ra 5173)
  listen 80;
  listen [::]:80;
  server_name secretpizza.io.vn www.secretpizza.io.vn;

  # Gốc chứa file build của React/Vite
  root /usr/share/nginx/html;
  index index.html;

  client_max_body_size 20m;

  # 1. Luồng gọi API
  location /api/ {
    proxy_pass http://backend:3001/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # 2. Luồng Real-time Socket.io
  location /socket.io/ {
    proxy_pass http://backend:3001/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # 3. Luồng load hình ảnh
  location /images/ {
    proxy_pass http://backend:3001/images/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # 4. Luồng xử lý Giao diện Frontend (React/Vite)
  location / {
    try_files $uri $uri/ /index.html;
  }
}